apiVersion: apps/v1
kind: Deployment
metadata:
  name: tf-gpu-shell
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tf-gpu-shell
  template:
    metadata:
      labels:
        app: tf-gpu-shell
    spec:
      restartPolicy: Always
      containers:
      - name: tf-gpu
        image: tensorflow/tensorflow:2.15.0-gpu
        command: ["/bin/bash", "-c"]
        args: ["sleep infinity"]
        resources:
          limits:
            nvidia.com/gpu: 1
            memory: 32Gi
            cpu: "16"
        volumeMounts:
        - name: dataset
          mountPath: /data
      volumes:
      - name: dataset
        persistentVolumeClaim:
          claimName: waymo-e2e-dataset

